# Generated by Django 6.0.3 on 2026-04-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_encoding',
        ),
    ]
